### ISSUE TITLE
@AbdealiJK is not featured on the team list

### ISSUE THREAD

**Issue by adtac** [coala/website-old#34]
But https://github.com/coala-analyzer/coala/graphs/contributors shows he has 461 commits.

![screenshot from 2016-04-27 11-49-02](https://cloud.githubusercontent.com/assets/7521600/14843507/6aeee162-0c6e-11e6-94b0-3bc04e0a26e0.png)

**Comment by sils** [comment]
Interesting...

![screenshot from 2016-04-27 08-23-46](https://cloud.githubusercontent.com/assets/5716520/14843538/636192ae-0c51-11e6-83ff-7203bdf0e982.png)

**Comment by SanketDG** [comment]
More interesting..
![kazam_screenshot_00024](https://cloud.githubusercontent.com/assets/8980971/14887278/b580ffd0-0d72-11e6-8400-29f43cc434c7.png)

CC @arafsheikh

**Comment by arafsheikh** [comment]
Okay this is weird. I found where the problem is though. 

@SanketDG you're probably using Chrome and @sils1297 is using Firefox. 

So the problem is with the parsing of the JSON returned by the API. Different browsers use different javascript engines and this is resulting in different output.

This shouldn't happen.

**Comment by adtac** [comment]
@arafsheikh FWIW I use Chrome too, if that'll be useful to solve this.

**Comment by tushar-rishav** [comment]
clearly I need to push more. :stuck_out_tongue_winking_eye:

**Comment by sils** [comment]
done at https://new.coala.io
